version: '3.6'
services:
  nest-crud:
    image: ghcr.io/turbolet85/first-nest-api/first-nest-api:develop
    container_name: nest-crud
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
